source 'https://rubygems.org'
ruby '2.1.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'spring',        group: :development
gem 'bcrypt-ruby', '~> 3.1.5'
gem 'warden'

group :doc do
  gem 'sdoc', require: false
end

group :test, :development do
  gem 'rspec-rails', '~> 2.14.2'
  gem 'database_cleaner'
end

group :test do
  gem 'capybara', '~> 2.1.0'
  gem 'factory_girl_rails', '~> 4.4.1'
end

